# .github/workflows/build.yml
name: Build Applications

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app PyQt6
          brew install create-dmg || true

      - name: Build macOS app
        run: python package_macos.py
